### ISSUE TITLE
Python setup.py test Error with azote@1.9.1:No module named 'gi',No module named 'common'

### ISSUE THREAD

**Issue by fubingting** [nwg-piotr/azote#145]
**Describe the bug**

**When I run python setup.py test for testing, the error is as follows,I have installed gtk3-devel**

ERROR: main (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: main
Traceback (most recent call last):
  File "/home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.8-v5y6jnp6vpdq4knxwsgnnsumzantggar/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/all_spack_env/spack_stage/root/spack-stage-py-azote-1.9.1-yaate3gsiv5ejhjpannyzzrud5l6kpxu/spack-src/azote/main.py", line 18, in <module>
    import common
ModuleNotFoundError: No module named 'common'

======================================================================
ERROR: plugins (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: plugins
Traceback (most recent call last):
  File "/home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.8-v5y6jnp6vpdq4knxwsgnnsumzantggar/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/all_spack_env/spack_stage/root/spack-stage-py-azote-1.9.1-yaate3gsiv5ejhjpannyzzrud5l6kpxu/spack-src/azote/plugins.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by nwg-piotr** [comment]
I'm not sure what you're trying to do. We don't have a package for CentOS, as far as I know.

**Comment by nwg-piotr** [comment]
Closing due to no feedback.
