### ISSUE TITLE
setup.py installation error

### ISSUE THREAD

**Issue by ordy** [nwg-piotr/azote#174]
**Describe the bug**
The package fails to install on Arch from both AUR and manual install.

**To Reproduce**
`yay -S azote` or `python setup.py install` from the current cloned repository.

**Screenshots**
![sc_21407](https://user-images.githubusercontent.com/22659443/224503378-1f5b41ff-f722-4a1c-a3b6-1856d491068d.png)

*Output*
```python
Traceback (most recent call last):
  File "/home/sano/.cache/yay/azote/src/azote-1.10.1/setup.py", line 9, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
    dist = MinimalDistribution(attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 57, in __init__
    super().__init__(filtered)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 486, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1021, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1018, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 943, in _normalized_name
    or super()._normalized_name
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

**Desktop:**
 - Linux distribution: Arch on 6.2.2-arch2-1 kernel (latest)
 - WM: sway

**Azote version:**
azote-1.10.1

**Additional context**
python: 3.10.9

Previous versions worked fine (from AUR). The issue seems to be only related to the install script because I can run azote just fine from `./azote/main.py`

**Comment by nwg-piotr** [comment]
Well, couldn't confirm. It installs on my both Arch machines. I tried in 3 ways: 

1. building with `makepkg` & installing with `# pacman -U azote-1.10.1-1-any.pkg.tar.zst`;
2. installing with `baph`;
3. installing with `yay`.

All went well.

**Comment by sgse** [comment]
From chotic-aur it work fine :slight_smile: , so AUR must work too.
Garuda Linux i3wm
~~~
pacman -Qi azote
Name                     : azote
Version                  : 1.10.1-1
Beschreibung             : Wallpaper & color manager for Sway, i3 and other WMs
~~~

**Comment by Whinery** [comment]
No issues installing azote on ArchLabs using Openbox.

**Comment by ordy** [comment]
@nwg-piotr Thank you for confirming. The problem was indeed on my side. My whole python site-packages lib was a total mess, took me a while to clean it up and now the install works as expected.

**Comment by nwg-piotr** [comment]
I'm glad you sorted it out.
